# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DevOps Library
email: admin@devopslibrary.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the DevOps Library!  We have the best videos for the best admins!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devopslibrary.com" # the base hostname & protocol for your site
twitter_username: devopslibrary
github_username:  kenerwin88
gems:
  - jekyll-redirect-from
# Build settings
markdown: kramdown

# Outputting
permalink: none

# Gem Addons
gems: [jekyll-redirect-from]

# Analytics
google_analytics_id: UA-60115428-1
